require File.expand_path('../../lib/checkers/piece', __FILE__)
require File.expand_path('../../lib/checkers/player', __FILE__)
require File.expand_path('../../lib/checkers/board', __FILE__)
require File.expand_path('../../lib/checkers/game', __FILE__)
require File.expand_path('../../lib/checkers/move', __FILE__)
require File.expand_path('../../lib/checkers/king', __FILE__)
require File.expand_path('../../lib/checkers/jump', __FILE__)
